# Generated by Django 3.0.3 on 2022-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20220203_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='54379', max_length=12),
        ),
    ]
