# Generated by Django 3.0.3 on 2022-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20220203_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='44317', max_length=12),
        ),
    ]
