# Generated by Django 3.0.3 on 2022-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20220203_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='24112', max_length=12),
        ),
    ]
