# Generated by Django 3.0.3 on 2022-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20220203_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='93943', max_length=12),
        ),
    ]
