# Generated by Django 3.0.3 on 2022-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_auto_20220203_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='93766', max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Member'), (2, 'Helper')], default=1),
        ),
    ]
