# Generated by Django 3.0.3 on 2022-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20220203_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='72376', max_length=12),
        ),
    ]
