# Generated by Django 3.0.3 on 2022-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_auto_20220203_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='33117', max_length=12),
        ),
    ]
