# Generated by Django 3.0.3 on 2022-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20220203_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='87143', max_length=12),
        ),
    ]
