# Generated by Django 3.0.3 on 2022-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_auto_20220203_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='65994', max_length=12),
        ),
    ]
