# Generated by Django 3.0.3 on 2022-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_auto_20220204_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='73741', max_length=12),
        ),
    ]
