# Generated by Django 3.0.3 on 2022-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_auto_20220204_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='31836', max_length=12),
        ),
    ]
