# Generated by Django 3.0.3 on 2022-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0057_auto_20220205_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='66372', max_length=12),
        ),
    ]
