# Generated by Django 3.0.3 on 2022-02-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_auto_20220205_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='52592', max_length=12),
        ),
    ]
