# Generated by Django 3.0.3 on 2022-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_auto_20220205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='16619', max_length=12),
        ),
    ]
