# Generated by Django 3.0.3 on 2022-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_auto_20220205_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='67626', max_length=12),
        ),
    ]
