# Generated by Django 3.0.3 on 2022-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_auto_20220205_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='29417', max_length=12),
        ),
    ]
