# Generated by Django 3.0.3 on 2022-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_auto_20220205_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='39799', max_length=12),
        ),
    ]
