# Generated by Django 3.0.3 on 2022-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_auto_20220205_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='42834', max_length=12),
        ),
    ]
