# Generated by Django 3.0.3 on 2022-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_auto_20220205_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='71523', max_length=12),
        ),
    ]
