# Generated by Django 3.0.3 on 2022-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_auto_20220206_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='99266', max_length=12),
        ),
    ]
