# Generated by Django 3.0.3 on 2022-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0070_auto_20220206_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='57226', max_length=12),
        ),
    ]
