# Generated by Django 3.0.3 on 2022-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0072_auto_20220206_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='66573', max_length=12),
        ),
    ]
