# Generated by Django 3.0.3 on 2022-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0075_auto_20220206_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='78125', max_length=12),
        ),
    ]
