# Generated by Django 3.0.3 on 2022-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0077_auto_20220207_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='59629', max_length=12),
        ),
    ]
