# Generated by Django 3.0.3 on 2022-02-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0079_auto_20220207_1518'),
        ('registration', '0077_auto_20220207_1324'),
    ]

    operations = [
    ]
