# Generated by Django 3.0.3 on 2022-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0080_merge_20220216_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='22121', max_length=12),
        ),
    ]
