name: ping-pong
dependencies:
  - python==3.7.6
  - psycopg2
  - pip
  - pip:
      - django==3.0.3
      - djangorestframework==3.11.0
      - djangorestframework_simplejwt==4.4.0
      - django-filter==2.2.0
      - coreapi==2.3.3
      - Markdown==3.2.1
      - Pygments==2.5.2
      - drf-yasg==1.20.0
      - Pillow==8.4.0
      - PyJWT==1.7.1
      - gunicorn==20.1.0
      - flake8
      - django-cors-headers==3.11.0

