# Generated by Django 3.0.3 on 2022-02-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20220203_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.SubCategory'),
        ),
    ]
