# Generated by Django 3.0.3 on 2022-02-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220203_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': ' Sub categories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, null=True, to='category.SubCategory'),
        ),
    ]
