# Generated by Django 3.0.3 on 2022-02-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20220203_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
