# Generated by Django 3.0.3 on 2022-02-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_auto_20220202_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Active'), (3, 'Completed')], default=1)),
                ('urgency', models.PositiveSmallIntegerField(choices=[(1, 'I can wait'), (2, 'Soon please'), (3, 'Emergency!')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_four', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_five', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_six', models.ImageField(blank=True, null=True, upload_to='')),
                ('helper_status', models.PositiveSmallIntegerField(choices=[(1, 'No response'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('private', models.BooleanField(default=False)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_category', to='category.Category')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_request', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
