# Generated by Django 3.0.3 on 2022-02-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_request', '0002_auto_20220204_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_review', to='member_request.MemberRequest')),
            ],
        ),
        migrations.CreateModel(
            name='HelperReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_review', to='member_request.MemberRequest')),
            ],
        ),
    ]
