# Generated by Django 3.0.3 on 2022-02-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_auto_20220203_2028'),
        ('member_request', '0003_helperreview_memberreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_category', to='category.Category'),
        ),
    ]
