# Generated by Django 3.0.3 on 2022-02-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_request', '0004_auto_20220205_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperreview',
            name='member_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_review', to='member_request.MemberRequest'),
        ),
        migrations.AlterField(
            model_name='memberreview',
            name='member_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_review', to='member_request.MemberRequest'),
        ),
    ]
