# Generated by Django 3.0.3 on 2022-02-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member_request', '0005_auto_20220205_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperreview',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberreview',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
