# Generated by Django 3.0.3 on 2022-02-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220202_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='helper_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='member_profile',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
