# Generated by Django 3.0.3 on 2022-02-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220202_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelperProfile',
        ),
    ]
