# Generated by Django 3.0.3 on 2022-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_helperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper_verify_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
