# Generated by Django 3.0.3 on 2022-02-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20220202_1456'),
        ('user', '0011_user_helper_verify_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_category', to='category.Category'),
        ),
    ]
