# Generated by Django 3.0.3 on 2022-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220202_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='helper_available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Busy'), (2, 'Not available')], default=1),
        ),
    ]
