# Generated by Django 3.0.3 on 2022-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20220203_0841'),
        ('user', '0015_auto_20220202_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='helper_category',
        ),
        migrations.AddField(
            model_name='user',
            name='helper_categories',
            field=models.ManyToManyField(blank=True, related_name='helper_category', to='category.Category'),
        ),
    ]
