# Generated by Django 3.0.3 on 2022-02-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220203_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='helper_sub_categories',
        ),
    ]
