# Generated by Django 3.0.3 on 2022-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220203_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper_hourly_rate',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
