# Generated by Django 3.0.3 on 2022-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_helper_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Member'), (2, 'Helper')]),
        ),
    ]
