# Generated by Django 3.0.3 on 2022-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220203_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zip',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
