# Generated by Django 3.0.3 on 2022-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20220204_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
