# Generated by Django 3.0.3 on 2022-02-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20220204_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postcode',
            new_name='zip',
        ),
    ]
